### ISSUE TITLE
Ordos campaign missions result in zero scores

### ISSUE THREAD

**Issue by juj** [henricj/dunelegacy#14]
Got this result after completing the second level of Ordos campaign by destroying the Harkonnen base:

![image](https://user-images.githubusercontent.com/225351/172058641-6f216513-4b72-4c8f-9a30-45b769332cd6.png)

I did not harvest the 2700 spice that was needed, but won by destroying the base. Had three harvesters during the mission, so harvested maybe 6-10 full harvester runs. Both sides definitely lost units, though I did not lose any buildings.

Not sure if this scoring mismatch generally happens on other/all missions - though definitely in that one.

**Comment by juj** [comment]
It does seem to occur systematically. Level 3 victory results looked the same:
![image](https://user-images.githubusercontent.com/225351/172059754-e5b16d80-dd49-4a57-88c6-9c27452bf713.png)

**Comment by henricj** [comment]
Those zeros look very suspicious.  I'm not sure why the game would end early, but the zero score is probably something I've broken recently in in [CampaignStatsMenu.cpp](https://github.com/henricj/dunelegacy/blame/modernize/src/Menu/CampaignStatsMenu.cpp).

**Comment by juj** [comment]
Completed the Ordos campaign, and looks like all missions did result in a zero score.

**Comment by juj** [comment]
The same issue is not occurring on Atreides campaign, but there the score screen does give out proper scores:

![image](https://user-images.githubusercontent.com/225351/172232802-13ebb5de-d384-4d3e-9d42-7cc6fa11006e.png)

**Comment by henricj** [comment]
Did you play the Ordos campaign with or without the (alleged) fix?
https://github.com/henricj/dunelegacy/commit/e38505b680513143abff8f92cfeba528f0cec223

**Comment by juj** [comment]
I think I played it without, Ordos build was from yesterday.

**Comment by juj** [comment]
Looks like this works now! Ordos campaign mission 1:

![image](https://user-images.githubusercontent.com/225351/172450423-436efb29-3dcc-4ad1-bc0d-34be4ba2018a.png)

Mission 2:

![image](https://user-images.githubusercontent.com/225351/172450459-6ed74903-76b9-4ca6-b129-9634110dfd72.png)

**Comment by juj** [comment]
The second Ordos mission still finished without needing to harvest the 2700 spice by destroying the Harkonnen base. Not sure if that is intentional or not:

![image](https://user-images.githubusercontent.com/225351/172450600-95caaa7a-1ec3-470b-922e-ad1a33962aa9.png)

Although I do kind of like that it is that way - kind of anticlimactic to have to farm 2700 right after having destroyed the enemy base. Although iirc Atreides level 2 is identical: "harvest 2700 and there's enemy base" - and there one does have to harvest up to 2700 even after destroying the base.

**Comment by henricj** [comment]
"Just hit F6 a couple of times."  More seriously, that is probably worth looking into.  If it says to harvest 2700, one should probably have to harvest 2700 before winning.  We should probably open another issue to track this win condition problem.
