### ISSUE TITLE
Mentat screen renders incorrectly

### ISSUE THREAD

**Issue by juj** [henricj/dunelegacy#17]
While applying the workaround from #16 , there are still some screens that lay out incorrectly. One of these is the Mentat help screen:

![image](https://user-images.githubusercontent.com/225351/172203834-aaecd2fc-1ee4-4e15-b2d8-4a485a690cea.png)

**Comment by henricj** [comment]
Could you try again with [this change (30082ac)](https://github.com/henricj/dunelegacy/commit/30082ac5fc7402fb30c52110593d802f5aa862cc)?

**Comment by henricj** [comment]
Thanks for checking.
