### ISSUE TITLE
CommandManager uses exceptions as control flow when loading a save game

### ISSUE THREAD

**Issue by juj** [henricj/dunelegacy#24]
I am running the game in a debug mode while attached to Visual Studio debugger in order to be able to catch any exceptions.

It looks like the implementation of `CommandManager::load()` which uses the `FileStream` object utilizes exception handling to implement control flow in order to know when the save file has finished loading.

This causes a debugger break every time when attempting to load a save game, breaking developer debugging cycle.

See 

![image](https://user-images.githubusercontent.com/225351/172437334-5776421d-4cb9-42eb-b17d-516e70274a08.png)

and its caller function

![image](https://user-images.githubusercontent.com/225351/172437398-9bec225a-d267-41b3-a5e7-1d4ae820a9d4.png)

I think it would be preferable to avoid this kind of a `while(true)` loop + throwing `eof` exceptions when interacting with `FileStream`, and instead have an API that queries the length of the file, and then loop until that end of file has been reached.

That would ease running the game with a debugger attached.

Not overly a big problem, though just thought to write down as to not lose any observations. I might propose a PR if you agree with the direction @henricj ?

**Comment by henricj** [comment]
Honestly, whenever I start looking at the serialization code I start itching to replace it all with [protobuf](https://developers.google.com/protocol-buffers) or some-such (along with [zstd](https://facebook.github.io/zstd/) or some other modern compression algorithm).  A couple of weeks ago, I even got as far as adding protobuf to the [vcpkg manifest](https://github.com/henricj/dunelegacy/blob/modernize/cmake/vcpkg.json) in a local branch.

The way the random number generation has changed, it has already broken compatibility with the [Sourceforge project](https://sourceforge.net/projects/dunelegacy/)'s save files (and yes, the file magic number and/or file extension should probably have been changed a while ago).

That said, I don't have anything against a PR to avoid throwing EOFs when there isn't actually an error.  My concerns would be more along the lines of how big an effort that would be versus replacing the serialization code and to understand how it might impact the serialization for the network (not that I've tested that code in years).
