### ISSUE TITLE
First mission is not won at 1000 credits

### ISSUE THREAD

**Issue by juj** [henricj/dunelegacy#35]
It looks like the first mission requires amassing 1300 spice instead of 1000 spice.

**Comment by juj** [comment]
Video to illustrate: https://youtu.be/LPxNgNO9PUc

**Comment by henricj** [comment]
I think it is won after harvesting 1000, not after reaching 1000 credits..?  What, exactly, does the mission text say?

**Comment by juj** [comment]
Doh! That is a very good point.

Level starts with 1000 credits, then Wind Trap is 300 credits, Refinery 400 credits, and you need to harvest 1000. So 1000 + 1000 - 300 - 400 = 1300.

Sorry for the noise!
