### ISSUE TITLE
Bad use after move

### ISSUE THREAD

**Issue by boris768** [henricj/dunelegacy#8]
https://github.com/henricj/dunelegacy/blob/4cc40be32d7229e66e5056249615392fbfcc75dd/src/CommandManager.cpp#L86-L87
https://github.com/henricj/dunelegacy/blob/4cc40be32d7229e66e5056249615392fbfcc75dd/src/FileClasses/POFile.cpp#L108-L109

dont use variables afrer [std::move](https://wiki.sei.cmu.edu/confluence/display/cplusplus/EXP63-CPP.+Do+not+rely+on+the+value+of+a+moved-from+object)

**Comment by henricj** [comment]
Thanks.

**Comment by henricj** [comment]
...and I just broke things with that "fix".
